In [2]:
import numpy as np
import sympy as sym


In [4]:
A = np.array(((1,3),(2,5)))
b = np.array([[10],[8]])

print("A:",'\n',A)
print("b:",'\n',b)

print("Solution:",'\n',np.linalg.solve(A,b))


A: 
 [[1 3]
 [2 5]]
b: 
 [[10]
 [ 8]]
Solution: 
 [[-26.]
 [ 12.]]


In [21]:
from sympy import MatrixSymbol, Matrix
X = MatrixSymbol('X', 3, 3)
Y = MatrixSymbol('Y', 3, 1)

Matrix(X)

Matrix(Y)

S = sym.MatMul(X,Y)

print("Solution:",'\n', Matrix(S))

Solution: 
 Matrix([[X[0, 0]*Y[0, 0] + X[0, 1]*Y[1, 0] + X[0, 2]*Y[2, 0]], [X[1, 0]*Y[0, 0] + X[1, 1]*Y[1, 0] + X[1, 2]*Y[2, 0]], [X[2, 0]*Y[0, 0] + X[2, 1]*Y[1, 0] + X[2, 2]*Y[2, 0]]])


In [19]:
X = MatrixSymbol('X', 3, 3)
Y = MatrixSymbol('Y', 3, 1)

Matrix(X)

Matrix([
[X[0, 0], X[0, 1], X[0, 2]],
[X[1, 0], X[1, 1], X[1, 2]],
[X[2, 0], X[2, 1], X[2, 2]]])

In [20]:
Matrix(Y)

Matrix([
[Y[0, 0]],
[Y[1, 0]],
[Y[2, 0]]])