Use Python to calculate the

In [6]:
import numpy as np

In [7]:
x = 35
list1 = [0]*35
count = 1
ind = 0

for i in range(x):
    list1[ind] = 20*count
    ind +=1
    count +=1
print(list1)

print(np.sum(list1))

[20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700]
12600


In [8]:

list1 = [0]*35
count = 1
ind = 0

for i in range(x):
    list1[ind] = 20*count
    ind +=1
    count +=1
print(list1)

print(np.sum(list1))

[20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700]
12600


In [9]:
array= np.array([[2,3,4],[5,6,7],[8,9,0]])
print(array)

[[2 3 4]
 [5 6 7]
 [8 9 0]]


In [10]:
print(array[:,0])

[2 5 8]


In [17]:
M = np.array([[2,3,4],[5,6,7],[8,9,0]])
count = 0 
newsum = 0

for j in np.arange(3):
    newsum += sum1 

    for i in range(1):
        sum1 = np.sum(M[count, :])
        count += 1
        #print(sum1)

print(newsum)

44
